platform :ios, '7.0'
target “ZTServiceProject” do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension'
#pod 'CYLTabBarController', '~> 1.6.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'YYCache', '~> 1.0.3'
pod 'GTMBase64', '~> 1.0.0'
pod 'UITableView+FDTemplateLayoutCell','~> 1.4'
pod 'IQKeyboardManager','~> 3.3.7'
pod 'TZImagePickerController'
pod 'RTRootNavigationController'
pod 'SDCycleScrollView'

end
